events {}

http {
    upstream app {
        server floodgate-app-1:8080;
        server floodgate-app-2:8080;
        server floodgate-app-3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }
    }
}